version: "3.7"

services:
    nginx:
        image: nginx:latest
        ports:
            - 8088:80
        links:
            - php-fpm
        volumes:
            - ./sites/test:/var/www/html
            - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build:
            context: .
            dockerfile: docker/PHP.Dockerfile
        volumes:
            - ./sites/test:/var/www/html
            - ./docker/conf/php.ini:/usr/local/etc/php/php.ini
    mariadb:
        image: mariadb
        volumes:
            - ./docker/db:/var/lib/mysql
            - ./docker/conf/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8765:80
        environment:
            - MYSQL_ROOT_PASSWORD=root
        depends_on:
            - mariadb
